# command line: main.py transfer -c .\config\fd\transfer.yaml

base_lr: 0.1
batch_size: 16
class_list: null
config: .\config\fd\transfer.yaml
cross_val: false
debug: false
device: 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn_fight.Model
model_args:
    dropout: 0
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 3
    num_class: 400
nesterov: true
num_epoch: 20
num_worker: 4
optimizer: SGD
pavi_log: false
phase: test
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step:
- 2
- 4
- 6
- 8
- 10
- 12
- 16
test_batch_size: 16
test_feeder_args:
    data_path: ./data/fight-detection/skeleton_3/val_data.npy
    label_path: ./data/fight-detection/skeleton_3/val_label.pkl
train_feeder_args:
    data_path: ./data/fight-detection/skeleton_3/train_data.npy
    label_path: ./data/fight-detection/skeleton_3/train_label.pkl
    random_choose: true
    random_move: true
    window_size: 300
train_full_feeder_args:
    data_path: ./data/fight-detection/skeleton_3/train_data_full.npy
    label_path: ./data/fight-detection/skeleton_3/train_label_full.pkl
    random_choose: true
    random_move: true
    window_size: 300
use_gpu: true
weight_decay: 0.0001
weights: ./models/st_gcn.kinetics.pt
work_dir: ./work_dir/recognition/fd/ST_GCN/0l
