weights: ./models/st_gcn.kinetics.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/fight-detection/skeleton/train_data.npy
  label_path: ./data/fight-detection/skeleton/train_label.pkl
  # data_path: ./data/Kinetics/kinetics-skeleton/train_data2.npy
  # label_path: ./data/Kinetics/kinetics-skeleton/train_label2.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'x
    strategy: 'spatial'